### PR TITLE
Capability map 1.5.8

### PR DESCRIPTION
**Pull request by shanecoughlan**
Begin to add tags for security... designed to help open discussion.

### CODE REVIEW

**Comment by shanecoughlan** [comment]
Some great feedback from the call. Core notes:

1. The work group currently has a strong focus on the how and when (details) of license compliance
2. There are open work items to refine further in that context
3. Adding security and/or export control would require some substantially different how and when items
4. So probably the best way forward is for the Security and Export Control Work Groups to start thinking through their domain items
5. And bring it to the Automation Work Group when they have context
6. And meanwhile Automation continues execution around license compliance with existing momentum

**Comment by shanecoughlan** [comment]
@jthDEV @OliverFendt my notes from our 2022-11-02 automation work group call above.

**Comment by shanecoughlan** [comment]
Suggestion: I will do a remix of this pull request with the optic of *not* including Security and Export Control here, but in splitting off forks to allow that. Pending updated PR.

**Comment by jthDEV** [comment]
Thank you Shane! I think, this is the best way to handle this. Maybe we could call the maps "Capability Map Licensing", Capability Map Security Assurance" and "Capability Map Export Controls" to link them to the corresponding workgroups.

**Pull request merged**
