### PR TITLE
docs(meeting): adding initial material for 20181017 meeting

### PR DESCRIPTION
**Pull request by mcjaeger**
Adding the meeting material as first version:

* minutes
* some notes on the goals
* first slides which were sent in

### CODE REVIEW

**Comment by OliverFendt** [comment]
Please correct the mark up for the agenda this looks very wired. 
Please convert the ppt of vulas in a pdf.

**Comment by OliverFendt** [comment]
Please correct the mark up for the agenda this looks very wired. 
Please convert the ppt of vulas in a pdf.

**Comment by mcjaeger** [comment]
thanks for pointing these out. I have corrected these. Should be better now.

**Comment by OliverFendt** [comment]
Looks fine
Although I get a Server error. Try later to merge

**Comment by OliverFendt** [comment]
Finale Merged after technicAl problems

**Pull request merged**
