### PR TITLE
docs(meetings): adding main slide document for meeting on 2019-01-24

### PR DESCRIPTION
**Pull request by mcjaeger**
adding main slide set to be added under the folders for the meeting material, main slide sets contains:
* agenda
* slides that I have presented

slides by other presenting persons can be put into the same folder

### CODE REVIEW

**Comment by OliverFendt** [comment]
looks good, but I think Slide 18 and 20 are identical. @mcjaeger  Perhaps you can remove slide 18?

**Comment by mcjaeger** [comment]
@OliverFendt, changed it, slides 18 and 20 are not identical anymore. I think I removed it, despite i realised later that it should have been a placeholder for mirko's slides.

**Comment by mcjaeger** [comment]
@OliverFendt could you pls. consider merging, i changes are OK?

**Comment by OliverFendt** [comment]
Meeting minutes

**Pull request merged**
