### PR TITLE
Initial draft for Use-Cases for next meeting in Darmstadt

### PR DESCRIPTION
**Pull request by mkurzman**
The use cases shall have a reference to the roles and activites described in the OpenChain Curriculum.
The use cases shall describe the "What". The User stories can be used to describe concrete features to be implemented in one sprint.
There is a description how use cases and user stories may be used together: https://www.visual-paradigm.com/guide/agile-software-development/user-story-vs-use-case/#integrate-use-case-user-story-and-story-map

### CODE REVIEW

**Comment by OliverFendt** [comment]
Thank you for contributing the use cases @mkurzman. For me is is currently not clear whether and how the use cases have any relationship to the user stories. If yes can you please specify what relationship they have. If not - I think we need such kind of relationship. Otherwise both efforts will be unaligned and cause confusion.

**Comment by OliverFendt** [comment]
That is a great idea to do the round trip. I am looking forward  to see the resultiert.  Thank you Marcel

**Comment by mcjaeger** [comment]
@mkurzman I am sorry for leaving this around for such a long time. Anything I could help with it? Kr, Michael

**Comment by shanecoughlan** [comment]
@mcjaeger @OliverFendt shall we reconsider actioning or rejecting this pull request?

**Comment by mcjaeger** [comment]
closing because of a lack of activity. @mkurzman please re-open if there is something I have missed....

**Pull request closed without merging**
